-- REQ-007 项目接入初始化闭环修复：补齐仓库索引表
-- 适用场景：已有需求平台库缺少 req_repository_index_batch、req_index_module 或 req_impact_item，
-- 导致 publish_repository_index 返回平台索引表未初始化错误。

CREATE TABLE IF NOT EXISTS req_repository_index_batch (
  batch_id BIGINT NOT NULL AUTO_INCREMENT,
  project_id BIGINT NOT NULL,
  repo_id BIGINT NOT NULL,
  repo_type VARCHAR(20) DEFAULT NULL,
  remote_url VARCHAR(500) NOT NULL,
  branch_name VARCHAR(100) NOT NULL,
  commit_hash VARCHAR(100) NOT NULL,
  index_version VARCHAR(32) NOT NULL,
  source_type VARCHAR(20) NOT NULL DEFAULT 'mcp',
  module_count INT NOT NULL DEFAULT 0,
  page_count INT NOT NULL DEFAULT 0,
  api_count INT NOT NULL DEFAULT 0,
  table_count INT NOT NULL DEFAULT 0,
  permission_count INT NOT NULL DEFAULT 0,
  document_count INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'imported',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME DEFAULT NULL,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (batch_id),
  KEY idx_req_index_batch_project (project_id),
  KEY idx_req_index_batch_repo (repo_id),
  KEY idx_req_index_batch_commit (repo_id, branch_name, commit_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='仓库索引批次';

CREATE TABLE IF NOT EXISTS req_index_module (
  index_module_id BIGINT NOT NULL AUTO_INCREMENT,
  batch_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  repo_id BIGINT NOT NULL,
  variant_id BIGINT DEFAULT NULL,
  parent_code VARCHAR(64) DEFAULT NULL,
  module_code VARCHAR(64) NOT NULL,
  module_name VARCHAR(100) NOT NULL,
  module_type VARCHAR(20) NOT NULL DEFAULT 'BUSINESS',
  repo_scope VARCHAR(20) NOT NULL DEFAULT 'ALL',
  relative_path VARCHAR(500) DEFAULT NULL,
  source_ref VARCHAR(500) DEFAULT NULL,
  summary VARCHAR(1000) DEFAULT NULL,
  order_num INT NOT NULL DEFAULT 0,
  status CHAR(1) NOT NULL DEFAULT '0',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME DEFAULT NULL,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (index_module_id),
  KEY idx_req_index_module_project (project_id),
  KEY idx_req_index_module_repo (repo_id),
  KEY idx_req_index_module_code (project_id, module_code),
  KEY idx_req_index_module_variant (project_id, variant_id, module_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='仓库索引模块知识';

CREATE TABLE IF NOT EXISTS req_impact_item (
  impact_id BIGINT NOT NULL AUTO_INCREMENT,
  batch_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  repo_id BIGINT NOT NULL,
  variant_id BIGINT DEFAULT NULL,
  branch_name VARCHAR(100) DEFAULT NULL,
  module_code VARCHAR(64) DEFAULT NULL,
  module_id BIGINT DEFAULT NULL,
  item_type VARCHAR(20) NOT NULL,
  item_name VARCHAR(200) NOT NULL,
  item_key VARCHAR(300) DEFAULT NULL,
  relative_path VARCHAR(500) DEFAULT NULL,
  http_method VARCHAR(20) DEFAULT NULL,
  api_path VARCHAR(300) DEFAULT NULL,
  permission_key VARCHAR(200) DEFAULT NULL,
  table_name VARCHAR(100) DEFAULT NULL,
  summary VARCHAR(1000) DEFAULT NULL,
  tags VARCHAR(500) DEFAULT NULL,
  status CHAR(1) NOT NULL DEFAULT '0',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME DEFAULT NULL,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (impact_id),
  KEY idx_req_impact_project_module (project_id, module_code),
  KEY idx_req_impact_variant_branch (variant_id, branch_name),
  KEY idx_req_impact_repo (repo_id),
  KEY idx_req_impact_type (item_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模块影响面索引';
